/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aldebaran_qi_Promise */

#ifndef _Included_com_aldebaran_qi_Promise
#define _Included_com_aldebaran_qi_Promise
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aldebaran_qi_Promise
 * Method:    _newPromise
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_aldebaran_qi_Promise__1newPromise
  (JNIEnv *, jobject);

/*
 * Class:     com_aldebaran_qi_Promise
 * Method:    _getFuture
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_aldebaran_qi_Promise__1getFuture
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_aldebaran_qi_Promise
 * Method:    _setValue
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_aldebaran_qi_Promise__1setValue
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_aldebaran_qi_Promise
 * Method:    _setError
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aldebaran_qi_Promise__1setError
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_aldebaran_qi_Promise
 * Method:    _setCanceled
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_aldebaran_qi_Promise__1setCancelled
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
